name: Kilted Binary Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 6 * * *'

jobs:
  kilted_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: testing
      ref_for_scheduled_build: main
